"use client"
import { Geist, Geist_Mono } from "next/font/google";
import { userDetailContext } from '../context/UserDetailContext';


import "./globals.css";
import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
   const [userDetail, setUserDetail] = useState(null);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <userDetailContext.Provider value={{
          userDetail, 
          setUserDetail
        }}>
          {children}
        </userDetailContext.Provider>
      </body>
    </html>
  );
}
